# Generated by Django 4.2.5 on 2023-09-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hokimiyat',
            name='murajat',
        ),
        migrations.AddField(
            model_name='hokimiyat',
            name='tel_name',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
